Running tests.py
at most 11 entries 
805400 entries in total
Traceback (most recent call last):
  File "tests.py", line 966, in <module>
    test_reprocess_corrected(run_reprocess=False, oneday=oneday)
  File "tests.py", line 169, in test_reprocess_corrected
    fineHCHO=gc.interp_to_grid(latmids,lonmids) * 1e-4 # molecules/m2 -> molecules/cm2
  File "/short/m19/jwg574/OMI_regridding/classes.py", line 116, in interp_to_grid
    newhcho=interp.ev(newlats,newlons)
  File "/apps/python3/3.5.2/lib/python3.5/site-packages/scipy/interpolate/fitpack2.py", line 954, in ev
    return self.__call__(xi, yi, dx=dx, dy=dy, grid=False)
  File "/apps/python3/3.5.2/lib/python3.5/site-packages/scipy/interpolate/fitpack2.py", line 834, in __call__
    x, y = np.broadcast_arrays(x, y)
  File "/apps/python3/3.5.2/lib/python3.5/site-packages/numpy-1.11.1-py3.5-linux-x86_64.egg/numpy/lib/stride_tricks.py", line 191, in broadcast_arrays
    shape = _broadcast_shape(*args)
  File "/apps/python3/3.5.2/lib/python3.5/site-packages/numpy-1.11.1-py3.5-linux-x86_64.egg/numpy/lib/stride_tricks.py", line 126, in _broadcast_shape
    b = np.broadcast(*args[:32])
ValueError: shape mismatch: objects cannot be broadcast to a single shape
